anthill:
  application:
    name: anthill-reactive-example
    version: 1.1.0-SNAPSHOT

spring:
  r2dbc:
    url: r2dbcs:mysql://192.168.1.188:3306/tec?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&SSL=false&sslMode=DISABLED
    username: root
    password: rootroot

logging:
  level:
    cn.chriswood.anthill: debug
