anthill:
  application:
    name: anthill-example-flex
    version: 0.0.1-SNAPSHOT
  mongo:
    enabled: false
    type: single
  aliyun-oss-sts:
    enabled: true
    oss:
      primary:
        region-id: cn-shanghai
        access-key-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-arn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-session-name: anthill-example
      cn-shanghai:
        region-id: cn-shanghai
        access-key-id: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        access-key-secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-arn: xxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        role-session-name: anthill-example
  #  redisson:
  #    enabled: true
  #    keyPrefix: ${anthill.application.name}
  #    # \u5355\u8282\u70B9\u914D\u7F6E
  #    singleServerConfig:
  #      # \u5BA2\u6237\u7AEF\u540D\u79F0
  #      clientName: ${anthill.application.name}
  #      # \u6700\u5C0F\u7A7A\u95F2\u8FDE\u63A5\u6570
  #      connectionMinimumIdleSize: 8
  #      # \u8FDE\u63A5\u6C60\u5927\u5C0F
  #      connectionPoolSize: 32
  #      # \u8FDE\u63A5\u7A7A\u95F2\u8D85\u65F6\uFF0C\u5355\u4F4D\uFF1A\u6BEB\u79D2
  #      idleConnectionTimeout: 10000
  #      # \u547D\u4EE4\u7B49\u5F85\u8D85\u65F6\uFF0C\u5355\u4F4D\uFF1A\u6BEB\u79D2
  #      timeout: 3000
  #      # \u53D1\u5E03\u548C\u8BA2\u9605\u8FDE\u63A5\u6C60\u5927\u5C0F
  #      subscriptionConnectionPoolSize: 50
  web:
    xss:
      enabled: false
    auth:
      excludes:
        - /
        # \u9759\u6001\u8D44\u6E90
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        # \u516C\u5171\u8DEF\u5F84
        - /favicon.ico
        # swagger \u6587\u6863\u914D\u7F6E
        - /*/api-docs
        - /*/api-docs/**
        # actuator \u76D1\u63A7\u914D\u7F6E
        - /actuator
        - /actuator/**
  swagger:
    title: ${anthill.application.name}
    version: ${anthill.application.version}
    description: ${anthill.application.version}
    contact:
      name: chriswoodcn
      email: chriswoodcn@aliyun.com

mybatis-flex:
  datasource:
    ds1:
      type: hikari
      url: jdbc:mysql://192.168.2.188:3307/anthill_example_jpa?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password: rootroot
    ds2:
      type: hikari
      url: jdbc:mysql://192.168.2.188:3307/anthill_example_jpa_slave?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B2
      username: root
      password: rootroot

logging:
  level:
    cn.chriswood.anthill.infrastructure: debug
    org.springframework.data.jpa: debug
  config: classpath:logback-spring.xml
  charset:
    file: UTF-8
server:
  port: 8081
spring:
  # \u8D44\u6E90\u4FE1\u606F
  messages:
    # \u56FD\u9645\u5316\u8D44\u6E90\u6587\u4EF6\u8DEF\u5F84
    basename: i18n/messages
  #    fix sa-token SpringBoot 3.x \u8DEF\u7531\u62E6\u622A\u9274\u6743\u62A5\u9519
  #    No more pattern data allowed after {*...} or ** pattern element
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #  jpa:
    #    show-sql: true
    #    properties:
    #      hibernate:
    #        hbm2ddl:
    #          auto: none
    #        query:
    #          mutation_strategy:
    #            global_temporary:
    #              create_tables: false
    #              drop_tables: false
    #        format_sql: true
    #  data:
    #    jpa:
    #      repositories:
    #        bootstrap-mode: DEFERRED #jpa\u542F\u52A8\u6A21\u5F0F\u4F18\u5316
#    redis:
#      repositories:
#        enabled: false
#      # \u5730\u5740
#      host: localhost
#      # \u7AEF\u53E3\uFF0C\u9ED8\u8BA4\u4E3A6379
#      port: 6379
#      # \u6570\u636E\u5E93\u7D22\u5F15
#      database: 2
#      # \u5BC6\u7801(\u5982\u6CA1\u6709\u5BC6\u7801\u8BF7\u6CE8\u91CA\u6389)
#      password: 123456
#      # \u8FDE\u63A5\u8D85\u65F6\u65F6\u95F4
#      timeout: 10s
#      # \u662F\u5426\u5F00\u542Fssl
#      ssl.enabled: false
#    mongodb:
#      uri: mongodb://admin:123456@127.0.0.1:27017/scootor_test?authSource=admin

#  datasource:
#    url: jdbc:mysql://192.168.1.188:3306/tec?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
#    username: root
#    password: rootroot
#    type: com.zaxxer.hikari.HikariDataSource


springdoc:
  #  default-flat-param-object: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: basic
      display-name: basic
      packages-to-scan:
        - cn.chriswood.anthill.example.flex.modules.basic
    - group: demo
      display-name: demo
      packages-to-scan:
        - cn.chriswood.anthill.example.flex.modules.demo



