anthill:
  application:
    name: BMM
    version: 1.0.0-SNAPSHOT
  jpa:
    enabled: true
    type: dynamic
    dynamic:
      primary:
        driver: ${configurations.PRIMARY_DRIVER}
        url: ${configurations.PRIMARY_DB_URL}
        username: ${configurations.PRIMARY_DB_USERNAME}
        password: ${configurations.PRIMARY_DB_PASSWORD}
        query: ${configurations.PRIMARY_DB_INIT_QUERY}

  swagger:
    enabled: true
    title: ${anthill.application.name}
    version: ${anthill.application.version}
    description: "电池信息管理系统后台"
    contact:
      name: chriswoodcn
      email: chriswoodcn@aliyun.com
  redisson:
    enabled: true
    keyPrefix: ${anthill.application.name}
    # 单节点配置
    singleServerConfig:
      # 客户端名称
      clientName: ${anthill.application.name}
      # 最小空闲连接数
      connectionMinimumIdleSize: 8
      # 连接池大小
      connectionPoolSize: 32
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
  web:
    invoke:
      enabled: true
    xss:
      enabled: true
      excludes: /system/notice/*
      urlPatterns: /system/*
    auth:
      excludes:
        - /
        # 静态资源
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        # 公共路径
        - /favicon.ico
        # swagger 文档配置
        - /swagger-ui/*
        - /*/api-docs
        - /*/api-docs/**
        # actuator 监控配置
        - /actuator
        - /actuator/**

# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期 设为一天 (必定过期) 单位: 秒
  timeout: 604800
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # 是否尝试从header里读取token
  is-read-header: true
  # 是否尝试从cookie里读取token
  is-read-cookie: false
  # token前缀
  #  token-prefix: "Bearer"
  # jwt秘钥
  jwt-secret-key: qazwsxedcrfvtgbyhnujm
  # 是否输出操作日志
  is-log: true

server:
  tomcat:
    uri-encoding: UTF-8
  port: 8080
  servlet:
    context-path: /

spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: local
  messages:
    basename: i18n/messages
  jpa:
    show-sql: ${configurations.SHOW_SQL}
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        query:
          mutation_strategy:
            global_temporary:
              create_tables: false
              drop_tables: false
        format_sql: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
    redis:
      repositories:
        enabled: false
      host: ${configurations.REDIS_HOST}
      port: ${configurations.REDIS_PORT}
      password: ${configurations.REDIS_PASSWORD}
      database: ${configurations.REDIS_DB}
      timeout: 10s
  flyway:
    enabled: ${configurations.FLYWAY_ENABLE}
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 1
    driver-class-name: ${configurations.PRIMARY_DRIVER}
    url: ${configurations.PRIMARY_DB_URL}
    user: ${configurations.PRIMARY_DB_USERNAME}
    password: ${configurations.PRIMARY_DB_PASSWORD}
    init-sqls: ${configurations.PRIMARY_DB_INIT_QUERY}


springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: COMMON
      display-name: COMMON
      packages-to-scan:
        - com.taotao.bmm.business.common
    - group: BACKEND
      display-name: BACKEND
      packages-to-scan:
        - com.taotao.bmm.business.backend
    - group: APP
      display-name: APP
      packages-to-scan:
        - com.taotao.bmm.business.APP

# actuator ??/actuator/health/liveness /actuator/health/readiness
# ref https://docs.spring.io/spring-boot/docs/3.2.0/reference/htmlsingle/#actuator.endpoints.kubernetes-probes
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
