= anthill-infrastructure-datasource

提供框架jpa动态数据源和多数据源配置支持

== Configurations
    anthill.jpa.enabled=true #默认开启srping-data-jpa配置

    #开启多数据源
    anthill.jpa.type=multi
    anthill.jpa.first.driver=xxx
    anthill.jpa.first.url=xxx
    anthill.jpa.first.username=xxx
    anthill.jpa.first.password=xxx
    anthill.jpa.first.query=xxx
    anthill.jpa.first.package-scan=xxx
    anthill.jpa.first.hikari.xx=xxx
    anthill.jpa.second.driver=xxx
    anthill.jpa.second.url=xxx
    anthill.jpa.second.username=xxx
    anthill.jpa.second.password=xxx
    anthill.jpa.second.query=xxx
    anthill.jpa.second.package-scan=xxx
    anthill.jpa.second.hikari.xx=xxx

    #开启动态数据源
    anthill.jpa.type=dynamic
    anthill.jpa.primary.driver=xxx
    anthill.jpa.primary.url=xxx
    anthill.jpa.primary.username=xxx
    anthill.jpa.primary.password=xxx
    anthill.jpa.primary.query=xxx
    anthill.jpa.primary.hikari.xx=xxx
    anthill.jpa.other.driver=xxx
    anthill.jpa.other.url=xxx
    anthill.jpa.other.username=xxx
    anthill.jpa.other.password=xxx
    anthill.jpa.other.query=xxx
    anthill.jpa.other.hikari.xx=xxx
