anthill:
  application:
    name: anthill-example
    version: 1.0.0-SNAPSHOT
  jpa:
    type: multi
    #    dynamic:
    #      primary:
    #        driver: com.mysql.cj.jdbc.Driver
    #        url: jdbc:mysql://192.168.1.188:3306/tec?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    #        username: root
    #        password: rootroot
    #        query: SELECT 1 FROM DUAL
    #      slave:
    #        driver: com.mysql.cj.jdbc.Driver
    #        url: jdbc:mysql://8.209.74.127:3306/scootor_mt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B2
    #        username: root
    #        password: TAOtao88888888
    #        query: SELECT 1 FROM DUAL
    multi:
      primary:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.1.188:3306/tec?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
        username: root
        password: rootroot
        query: SELECT 1 FROM DUAL
        dialect: org.hibernate.dialect.MySQLDialect
        package-scan: cn.chriswood.anthill.example.persistence.primary
      second:
        driver: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/scootor_mt?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B2
        username: root
        password: rootroot
        query: SELECT 1 FROM DUAL
        dialect: org.hibernate.dialect.MySQLDialect
        package-scan: cn.chriswood.anthill.example.persistence.other
  redisson:
    enabled: true
    keyPrefix: ${anthill.application.name}
    # 单节点配置
    singleServerConfig:
      # 客户端名称
      clientName: ${anthill.application.name}
      # 最小空闲连接数
      connectionMinimumIdleSize: 8
      # 连接池大小
      connectionPoolSize: 32
      # 连接空闲超时，单位：毫秒
      idleConnectionTimeout: 10000
      # 命令等待超时，单位：毫秒
      timeout: 3000
      # 发布和订阅连接池大小
      subscriptionConnectionPoolSize: 50
  web:
    xss:
      enabled: false
    auth:
      excludes:
        # 静态资源
        - /*.html
        - /**/*.html
        - /**/*.css
        - /**/*.js
        # 公共路径
        - /favicon.ico
        - /error
        # swagger 文档配置
        - /*/api-docs
        - /*/api-docs/**
        # actuator 监控配置
        - /actuator
        - /actuator/**
  swagger:
    info:
      title: ${anthill.application.name}
      version: ${anthill.application.version}
      description: 'anthill-example'
      contact:
        name: chriswoodcn
        email: chriswoodcn@aliyun.com

logging:
  level:
    cn.chriswood.anthill.infrastructure: debug
    org.springframework.data.jpa: debug

spring:
  #  fix sa-token SpringBoot 3.x 路由拦截鉴权报错
  #  No more pattern data allowed after {*...} or ** pattern element
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        query:
          mutation_strategy:
            global_temporary:
              create_tables: false
              drop_tables: false
        format_sql: true
  data:
    jpa:
      repositories:
        bootstrap-mode: DEFERRED #jpa启动模式优化
    redis:
      # 地址
      host: localhost
      # 端口，默认为6379
      port: 6379
      # 数据库索引
      database: 0
      # 密码(如没有密码请注释掉)
      # password:
      # 连接超时时间
      timeout: 10s
      # 是否开启ssl
      ssl.enabled: false


springdoc:
  default-flat-param-object: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: sys
      display-name: sys
      packages-to-scan:
        - cn.chriswood.anthill.example.modules.sys


